CREATE DATABASE INNOVARTE

Create TABLE ARTESANOS(
    ID SMALLSERIAL PRIMARY KEY NOT NULL,
    RUT VARCHAR(12) UNIQUE,
    CONTRASENA VARCHAR(25),
    NOMBRE VARCHAR(50),
    RUBRO VARCHAR(30),
    NUMERO_TELEFONO VARCHAR (12),
    DIRECCION VARCHAR (55),
    DESCRIPCION VARCHAR (300)
    );
    
Create TABLE PRODUCTOS(
    ID SMALLSERIAL PRIMARY KEY NOT NULL,
    PRECIO INT2,
    ID_ARTESANO INT2,
    MATERIAL VARCHAR(40),
    CATEGORIA VARCHAR(40),
    DESCRIPCION VARCHAR(75),
    FOREIGN KEY(ID_ARTESANO)
    REFERENCES ARTESANOS(ID)
)
Create TABLE REDES(
    WHATSAPP VARCHAR (30),
    FACEBOOK VARCHAR (60),
    INSTAGRAM VARCHAR (60),
    CORREO VARCHAR (60),
    LOGO VARCHAR (60),
    PAGINA_WEB VARCHAR (60),
    HORARIO VARCHAR (25),
    ID_ARTESANO INT2,
    FOREIGN KEY(ID_ARTESANO)
    REFERENCES ARTESANOS(ID)
)

Create TABLE IMAGENES_P(
ID SMALLSERIAL PRIMARY KEY NOT NULL,
ID_PRODUCTOS INT2   ,
IMAGEN_P BYTEA,
FOREIGN KEY(ID_PRODUCTOS)
REFERENCES PRODUCTOS(ID)


Create TABLE IMAGENES_A(
ID SMALLSERIAL PRIMARY KEY NOT NULL,
ID_ARTESANO INT2   ,
IMAGEN_P BYTEA,
FOREIGN KEY(ID_ARTESANO)
REFERENCES ARTESANOS(ID)
)

Create TABLE CATEGORIAS()
ID SMALLSERIAL PRIMARY KEY NOT NULL,

//ejemplos
INSERT INTO ARTESANOS VALUES(DEFAULT,'19339408-6','lololo123','silvio vera', 'programador','+56956216300','sol naciente 192',-33.000961,-71.484109,'prueba generica');
